Repository syrus-bot/syrus-bot, pull requests merged in 2020-12, with the labels that each got.

#35 push core changes upstream
  .eslintrc.json
  CONTRIBUTING.md
  src/commands/Utility/info.js
  src/lib/structures/MusicManager.js
  src/main.js
  src/providers/mongodb.js
Labels: priority: urgent

#37 fix(music): fix errors with disconnecting
  src/commands/Music/disconnect.js
  src/lib/structures/MusicManager.js
Labels: bug, priority: low

#42 feat(checks): add full suite cascading predicates
  src/commands/Core/eval.js
  src/commands/Core/kill.js
  src/commands/Core/reload.js
  src/commands/Core/set.js
  src/commands/Moderation/ban.js
  src/commands/Moderation/kick.js
  src/commands/Moderation/lockdown.js
  src/commands/Moderation/purge.js
  src/commands/Moderation/unlock.js
  src/commands/Utility/delrole.js
  src/commands/Utility/invite.js
  src/commands/Utility/pin.js
  src/commands/Utility/role.js
  src/commands/Utility/topic.js
  src/commands/Utility/vote.js
  src/preconditions/Admin.js
  src/preconditions/DJ.js
  src/preconditions/Mod.js
  src/preconditions/Owner.js
  src/preconditions/ServerOwner.js
  src/preconditions/owner.js
  src/preconditions/permissions.js
  src/providers/mongodb.js
Labels: feat: core, priority: medium

#43 ci(lint): standardise settings
  .eslintrc.json
  src/arguments/category.js
  src/arguments/command.js
  src/commands/Core/eval.js
  src/commands/Core/help.js
  src/commands/Core/kill.js
  src/commands/Core/reload.js
  src/commands/Fun/pp.js
  src/commands/Fun/sus.js
  src/commands/Moderation/ban.js
  src/commands/Moderation/kick.js
  src/commands/Moderation/lockdown.js
  src/commands/Moderation/purge.js
  src/commands/Moderation/unlock.js
  src/commands/Music/disconnect.js
  src/commands/Music/join.js
  src/commands/Music/np.js
  src/commands/Music/pause.js
  src/commands/Music/play.js
  src/commands/Music/resume.js
  src/commands/Music/skip.js
  src/commands/Music/stop.js
  src/commands/Music/volume.js
  src/commands/Utility/avatar.js
  src/commands/Utility/choose.js
  src/commands/Utility/delrole.js
  src/commands/Utility/info.js
  src/commands/Utility/pin.js
  src/commands/Utility/role.js
  src/commands/Utility/topic.js
  src/commands/Utility/vote.js
  src/lib/structures/CommandStore.js
  src/lib/structures/MusicManager.js
  src/lib/structures/SyrusClient.js
  src/lib/structures/SyrusCommand.js
  src/providers/mongodb.js
Labels: meta, priority: medium

#49 test: implement unit testing
  .github/workflows/check-code-style.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/semver-bump.yml
  .github/workflows/test-coverage.yml
  .gitignore
  package-lock.json
  package.json
  src/bot.js
  src/commands/Core/eval.js
  src/config.example.json
  src/config.json.example
  src/events/onceReady.js
  src/lib/structures/CommandStore.js
  src/lib/structures/MusicManager.js
  src/lib/structures/SyrusClient.js
  src/providers/mongodb.js
  test/command-framework.test.js
  test/providers.test.js
Labels: feat: core, priority: urgent

#40 feat(commands): implement fun
  src/commands/Fun/8ball.js
  src/commands/Fun/clap.js
  src/commands/Fun/dadjoke.js
  src/commands/Fun/owoify.js
  src/commands/Fun/wikihow.js
  src/config.example.json
  src/languages/en-us/fun.json
Labels: priority: medium
